name: Bangla Development Resources

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9.6
    
    - name: Installing Dependencies
      run: pip install -r requirements.txt

    - name: Copy files to docs directory
      run: |
        cp README.md docs/index.md
        cp CONTRIBUTING.md docs/CONTRIBUTING.md

    - name: Run build tasks
      run: mkdocs build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
